library(ggplot2)
library(tidyverse)
file<-read.csv("uber-raw-data-sep14.csv")
head(file)
file$Date.Time <- as.POSIXct(file$Date.Time, format="%m/%d/%Y %H:%M:%S", tz="GMT")
file$Dayofweek<-weekdays(as.Date(file$Date.Time))
file$Daynumber<-format(file$Date.Time, format = "%d")
file$Hour<-format(file$Date.Time, format = "%H")
ggplot(file,aes(Daynumber))+geom_bar(width = 0.5, color="Green")+geom_density(aes(x=Daynumber,y=..density..),alpha=0.7)+theme_classic()
ggplot(file,aes(Hour))+geom_bar(width = 0.5, color="Green")+geom_density(aes(x=Hour,y=..density..),alpha=0.7)+theme_classic()
ggplot(file,aes(Dayofweek))+geom_bar(width = 0.5, color="Green")+geom_density(aes(x=Dayofweek,y=..density..),alpha=0.7)+theme_classic()
ggplot(file,aes(Hour,Dayofweek))+geom_bin2d(binwidth = c(0.25, 500))
ggplot(file,aes(Lon,Lat),title(main = "Uber Trip Analysis"),)+geom_point(color="Steel Blue",size=2,alpha=0.8)
